#! /bin/bash
# Release current libpqxx trunk (or other branch).
# Arguments:
#   <new version number> [parent]
#
# The parent branch defaults to "trunk."
set -e

NEWVERSION="$1"
if test -z "$NEWVERSION"
then
	echo "Usage: $0 <new-version>" >&2
	exit 1
fi

PARENT="$2"
if test -z "$PARENT"
	PARENT="trunk"
fi

REPO="file://localhost/srv/svn/libpqxx"
#REPO="svn+ssh://pqxx.org/srv/svn/libpqxx/"
FTP="/srv/ftp/libpqxx"
SNAPSHOT="/home/jtv/public_html/tmp/pqxx/snapshot"
DOC="/srv/www/devprojects/libpqxx/doc"

CHECKOUT="`mktemp -p /tmp -d pqxx.XXXXXXXXXX`"
echo "** Checking out source tree to $CHECKOUT **"
cd "$CHECKOUT"
svn co -q "$REPO"
cd libpqxx/

export PATH="$PATH:$CHECKOUT/libpqxx/$PARENT/tools"

pushd "$PARENT" >/dev/null
PQXXVERSION="`extract_version`"
popd >/dev/null

if test "$PQXXVERSION" = "$NEWVERSION"
then
	echo "Given new version is same as existing version." >&2
	exit 2
fi

RELEASEDATE="`date +'%a, %d %b %y %T %z'`"

echo "** Updating source tree **"
svn cp "$PARENT" "tags/$PQXXVERSION"

# Mark new trunk in debian/changelog
TEMPCHANGELOG="`mktemp`"
cat - <<EOF "$PARENT"/debian/changelog >"$TEMPCHANGELOG"
libpqxx ($NEWVERSION-1) unstable; urgency=medium

  * Forked release $PQXXVERSION.

 -- Jeroen T. Vermeulen <jtv@xs4all.nl>  $RELEASEDATE

EOF
mv "$TEMPCHANGELOG" "$PARENT"/debian/changelog

# Mark new version in NEWS
TEMPNEWS="`mktemp`"
cat - <<EOF "$PARENT/NEWS" >"$TEMPNEWS"
$NEWVERSION
EOF
mv "$TEMPNEWS" "$PARENT"/NEWS

echo "PQXX_VERSION	$NEWVERSION" >"$PARENT"/VERSION

svn commit -m "Forking release $PQXXVERSION, moving on to $NEWVERSION."
cd /tmp
rm -rf -- "$CHECKOUT"


echo "** Setting up new documentation **"
TEMPDOC="`mktemp -p /tmp -d pqxxdoc.XXXXXXXXXX`"
cd "$TEMPDOC"
tar xzf "$SNAPSHOT"/libpqxx-*.tar.gz
cd libpqxx-*/

PREVIOUS=''
for d in `ls "$DOC" | grep '[0-9]'`
do
	PREVIOUS="$PREVIOUS --link-dest='$d'"
done

rsync -r $PREVIOUS doc/html "$DOC/$PQXXVERSION"

cd /tmp
rm -rf "$TEMPDOC"

if test "$PARENT" = "trunk"
then
	# Move snapshot tarball to FTP directory.
	mv "$SNAPSHOT"/libpqxx-*.tar.* "$FTP/"
else
	echo "*** Remember: Build tarball and make available for upload ***"
fi

echo "** Done **"
