# Read the Docs configuration file.
#
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details.

---
version: 2

build:
  # Using an old Ubuntu LTS: an apparent bug in Doxygen 1.9.8 "loses" the
  # documentation for pqxx::transaction and pqxx::work.  So for now, stick
  # with Doxygen 1.9.1.  :-(
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - "autoconf"
    - "automake"
    - "build-essential"
    - "graphviz"
    - "libpq-dev"
    - "make"
  jobs:
    pre_build:
      - "./configure CXXFLAGS=\"-O0 -std=c++23\" --enable-documentation"
      - "mkdir -p doc/doxygen-html"
      - "doxygen"
      - "mkdir -p -- \"$READTHEDOCS_OUTPUT/html\""
    post_build:
      - "cd -- \"$READTHEDOCS_OUTPUT\" && mv html sphinx-html"
      - "mv -- doc/doxygen-html \"$READTHEDOCS_OUTPUT/html\""


python:
  install:
    - requirements: doc/requirements.txt

sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: true
