#define PQXX_HAVE_PQESCAPEBYTEA 1
#define PQXX_HAVE_PQESCAPESTRING 1
/* #undef PQXX_HAVE_PQEXECPREPARED */
#define PQXX_HAVE_PQFREEMEM 1
#define PQXX_HAVE_PQFREENOTIFY 1
#define PQXX_HAVE_PQPUTCOPY 1
#define PQXX_HAVE_PQRESULTERRORFIELD 1
#define PQXX_HAVE_PQUNESCAPEBYTEA 1
