#define PQXX_HAVE_LO_TELL 1
/* #undef PQXX_HAVE_PQCANCEL */
#define PQXX_HAVE_PQCLIENTENCODING 1
/* #undef PQXX_HAVE_PQDESCRIBEPORTAL */
/* #undef PQXX_HAVE_PQENCRYPTPASSWORD */
/* #undef PQXX_HAVE_PQESCAPEBYTEA */
#define PQXX_HAVE_PQESCAPEBYTEACONN 1
#define PQXX_HAVE_PQESCAPESTRING 1
#define PQXX_HAVE_PQESCAPESTRINGCONN 1
/* #undef PQXX_HAVE_PQEXECPARAMS */
/* #undef PQXX_HAVE_PQEXECPREPARED */
/* #undef PQXX_HAVE_PQFREEMEM */
/* #undef PQXX_HAVE_PQFREENOTIFY */
/* #undef PQXX_HAVE_PQFTABLE */
/* #undef PQXX_HAVE_PQFTABLECOL */
/* #undef PQXX_HAVE_PQISTHREADSAFE */
#define PQXX_HAVE_PQMBLEN 1
/* #undef PQXX_HAVE_PQPREPARE */
/* #undef PQXX_HAVE_PQPROTOCOLVERSION */
/* #undef PQXX_HAVE_PQPUTCOPY */
/* #undef PQXX_HAVE_PQRESULTERRORFIELD */
/* #undef PQXX_HAVE_PQSERVERVERSION */
/* #undef PQXX_HAVE_PQSETERRORVERBOSITY */
/* #undef PQXX_HAVE_PQUNESCAPEBYTEA */
