#! /bin/sh
set -eu

ARG="${1:-}"

case "$ARG" in
'')
	MODE="lib"
	;;
-h|--help)
	cat <<EOF
Usage: $0 [-a|--abi]

Prints the full library version by default.  If the --abi option is given,
prints the library's ABI version instead.
EOF
	exit
	;;
-a|--abi)
	MODE="abi"
	;;
*)
	cat <<EOF >&2
Unknown argument.  Try

	$0 --help

for usage information.
EOF
	exit 1
esac


case "$MODE" in
lib)
	cat VERSION
	;;
abi)
	cat VERSION | sed -e 's/\([^.]*\.[^.]*\)\..*/\1/'
	;;
*)
	echo "Unknown mode." 2>&1
	exit 2
	;;
esac
