#! /bin/sh
#
# Reformat source code using clang-format.

set -C -u -e

# Reformat C++ files.
find -name \*.cxx -o -name \*.hxx | xargs clang-format -i


# Reformat CMake files.
WORKDIR=$(mktemp -d)
virtualenv -q --python=$(which python3) "$WORKDIR/venv"
. "$WORKDIR/venv/bin/activate"
pip install -q six pyaml cmake-format
(find -name CMakeLists.txt | xargs cmake-format -i) || /bin/true
rm -rf "$WORKDIR"
