#! /bin/sh
#
# Reformat source code using clang-format.

set -C -u -e

# Reformat C++ files.
find -name \*.cxx -o -name \*.hxx | xargs clang-format -i


# Reformat CMake files.
#WORKDIR=$(mktemp -d)
#virtualenv "$WORKDIR/venv"
#. "$WORKDIR/venv/bin/activate"
#pip install six
#pip install pyaml
#pip install cmake-format
#find -name CMakeLists.txt -o -name CMakeLists.template |
    #xargs cmake-format -i
#rm -rf "$WORKDIR"
