// Feature tests generated by generate_cxx_checks.py.
#include <version>
#if defined(__cpp_concepts) && __cpp_concepts
auto pqxx_have_concepts = true;
#else
auto pqxx_have_concepts = false;
#endif
#if defined(__cpp_multidimensional_subscript) && __cpp_multidimensional_subscript
auto pqxx_have_multidim = true;
#else
auto pqxx_have_multidim = false;
#endif
#if defined(__cpp_lib_source_location) && __cpp_lib_source_location
auto pqxx_have_source_location = true;
#else
auto pqxx_have_source_location = false;
#endif
#if defined(__cpp_lib_span) && __cpp_lib_span
auto pqxx_have_span = true;
#else
auto pqxx_have_span = false;
#endif
#if defined(__cpp_lib_ssize) && __cpp_lib_ssize
auto pqxx_have_ssize = true;
#else
auto pqxx_have_ssize = false;
#endif
#if defined(__cpp_lib_unreachable) && __cpp_lib_unreachable
auto pqxx_have_unreachable = true;
#else
auto pqxx_have_unreachable = false;
#endif
