// Feature check for 'PQXX_HAVE_UNREACHABLE'.
// Generated by generate_cxx_checks.py.
#include <version>
#if !defined(__cpp_lib_unreachable) || !__cpp_lib_unreachable
#error "No support for PQXX_HAVE_UNREACHABLE detected: __cpp_lib_unreachable not set."
#endif

int main() {}
