// Feature check for 'PQXX_HAVE_SSIZE'.
// Generated by generate_cxx_checks.py at 2023-11-12 22:45:48.721993+00:00 UTC.
#include <version>
#if !defined(__cpp_lib_ssize) || !__cpp_lib_ssize
#error "No support for PQXX_HAVE_SSIZE detected: __cpp_lib_ssize not set."
#endif

int main() {}
