// Feature check for '__cpp_concepts'.
// Generated by generate_cxx_checks.py at 2023-11-11 02:23:59.388992 UTC.
#include <version>
#if !defined(PQXX_HAVE_CONCEPTS) || !PQXX_HAVE_CONCEPTS
#error "No support for __cpp_concepts detected."
#endif

int main() {}
