// Feature check for 'PQXX_HAVE_MULTIDIM'.
// Generated by generate_cxx_checks.py at 2023-11-12 22:27:55.091985+00:00 UTC.
#include <version>
#if !defined(__cpp_multidimensional_subscript) || !__cpp_multidimensional_subscript
#error "No support for PQXX_HAVE_MULTIDIM detected: __cpp_multidimensional_subscript not set."
#endif

int main() {}
