// Feature check for 'PQXX_HAVE_SOURCE_LOCATION'.
// Generated by generate_cxx_checks.py at 2023-11-12 22:45:48.721993+00:00 UTC.
#include <version>
#if !defined(__cpp_lib_source_location) || !__cpp_lib_source_location
#error "No support for PQXX_HAVE_SOURCE_LOCATION detected: __cpp_lib_source_location not set."
#endif

int main() {}
