// Feature check for '__cpp_lib_source_location'.
// Generated by generate_cxx_checks.py at 2023-11-11 02:23:59.389166 UTC.
#include <version>
#if !defined(PQXX_HAVE_SOURCE_LOCATION) || !PQXX_HAVE_SOURCE_LOCATION
#error "No support for __cpp_lib_source_location detected."
#endif

int main() {}
