// Feature check for 'PQXX_HAVE_SPAN'.
// Generated by generate_cxx_checks.py at 2023-11-12 22:45:48.721993+00:00 UTC.
#include <version>
#if !defined(__cpp_lib_span) || !__cpp_lib_span
#error "No support for PQXX_HAVE_SPAN detected: __cpp_lib_span not set."
#endif

int main() {}
