// Feature check for 'PQXX_HAVE_SSIZE'.
// Generated by generate_cxx_checks.py.
#include <version>
#if !defined(__cpp_lib_ssize) || !__cpp_lib_ssize
#error "No support for PQXX_HAVE_SSIZE detected: __cpp_lib_ssize not set."
#endif

int main() {}
