// Feature check for 'PQXX_HAVE_SSIZE'.
// Generated by generate_cxx_checks.py.
#include <version>
#if !defined(__cpp_lib_ssize)
#  error "No PQXX_HAVE_SSIZE: __cpp_lib_ssize is not set."
#endif
#if !__cpp_lib_ssize
#  error "No PQXX_HAVE_SSIZE: __cpp_lib_ssize is false."
#endif

int main() {}
