// Feature check for '__cpp_multidimensional_subscript'.
// Generated by generate_cxx_checks.py at 2023-11-11 02:23:59.389103 UTC.
#include <version>
#if !defined(PQXX_HAVE_MULTIDIM) || !PQXX_HAVE_MULTIDIM
#error "No support for __cpp_multidimensional_subscript detected."
#endif

int main() {}
