name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

permissions:
  contents: read

jobs:
  stale:

    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'There has been no activity on this ticket.  Consider closing it.'
        stale-pr-message: 'There has been no activity on this pull request.  Complete it or drop it.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
